### ISSUE TITLE
No indication of whether photos have been added or not

### ISSUE THREAD

**Issue by yaswant2403** [CS196Illinois/FA24-Group21#16]
Currently, when a user presses Add Photos, there is no indication of whether the photo has been added or not to the user. There could be many ways to indicate this. Here are some possible solutions:

- Implement a counter that keeps track of the number of photos in the photos array so that user knows how many (if any) photos have been uploaded
- Have a thumbnail preview of photos uploaded that appears above the Add Photos button

**Comment by Howardc3** [comment]
There is now a thumbnail preview of the pictures selected. Instead of showing the number of pictures going to be submitted, there is a delete button that clears the selections.

**Comment by yaswant2403** [comment]
Great work!
