### ISSUE TITLE
Date/Time Picker

### ISSUE THREAD

**Issue by yaswant2403** [CS196Illinois/FA24-Group21#17]
Currently, Time is solely dependent on the current time and day. Having the option for the user to choose their date and time would be great. 

This might be of use: https://mui.com/x/react-date-pickers/date-time-picker/
Installation: https://mui.com/x/react-date-pickers/getting-started/#installation 
(use npx expo install <packages> instead of npm. However, if that doesn't work, then use npm)

**Comment by Howardc3** [comment]
I'll work on that more tonight or tomorrow. I tried to get it to work yesterday, but I kept running into weird errors that seemed to be an issue with my initial installation of Material UI.

**Comment by Howardc3** [comment]
I ran into the same error today trying to use the DateTimePicker and apparently other people have experienced the same thing.  From this [thread ](https://github.com/mui/mui-x/issues/10772 )and [this ](https://github.com/mui/mui-x/issues/10732)one it seems like the problem lies with the React version? I might look for a different picker.

**Comment by yaswant2403** [comment]
Hmm, based on those issues, it seems like `navigator` might be the underlying issue which is unfortunate because Expo doesn't mesh well with `navigator`. They prefer users use `router` from `expo-router`. And we're not gonna go in and change how mui built it, so yea it might be better to look for a different picker. 

I'll also take a look at it tn and mess around with mui's picker.

**Comment by yaswant2403** [comment]
https://github.com/react-native-datetimepicker/datetimepicker might be useful

**Comment by Howardc3** [comment]
Ok, I have incorporated the date time picker to allow the user to pick the date and time and I pushed all of that into my branch!

**Comment by yaswant2403** [comment]
Great! I'll merge into the main branch and close the issue once it's been merged!

**Comment by yaswant2403** [comment]
@Howardc3 Just a heads-up. Adding a package to your package-lock.json so you might have a slight hiccup when pulling/pushing to your remote branch. But, it's just one line so you should be able to copy and paste it
