### ISSUE TITLE
Extension of #17 to include Now Button

### ISSUE THREAD

**Issue by yaswant2403** [CS196Illinois/FA24-Group21#28]
Currently, user has to manually type in a date and time. Having the option to automatically set the date and time to current date and time would be great. A mockup of where the button could be implemented is shown below:
![image](https://github.com/user-attachments/assets/0514180e-efa1-41d1-8241-d3e44e3f08db)

**Comment by Howardc3** [comment]
I have added a now button!

**Comment by yaswant2403** [comment]
Great work!
